ci/cd: simplify and refactor workflows
stakater/application pull request #246
Opened 2023-04-02 15:38 UTC by d3adb5

We discussed switching from running a dry-run install on the Single Node OpenShift clusters as self-hosted runners and instead using kind or k0s.

This PR changes the CI and CD workflows to use kind for a dry-run. The CI workflow is now invoked from the CD workflow to avoid repetition, and Tilt has been removed altogether since I couldn't see why the Tilt setup was necessary.

Bringing back the Tilt files should be as easy as running `git revert` on 645165f. If we end up having to use it again, that's how we can restore them.

Additionally, linting, unit testing, and the dry run install happen in parallel now. Only the latter needs a cluster, so that's where we bring up kind. For now, since we're not testing specific cluster topologies, no cluster configuration has been added.

2023-04-02 15:41 UTC, d3adb5 commented
It seems every time I read over the documentation and reference for GitHub Actions I find something has changed. I'd love to get some input from everybody on these changes. @rasheedamir @aslafy-z @slauger Can you guys leave a review?

The updated actions won't run here until merged, so I tested them on my fork:

- https://github.com/d3adb5/application/actions/runs/4589451185
- https://github.com/d3adb5/application/actions/runs/4589447205

And in the `#testing-pr-notifications` channel on Stakater's Slack community.

2023-04-02 15:42 UTC, d3adb5 commented
About the failed status check: the Tilt files were removed in this PR, so `tilt ci` will definitely fail. I'm not sure how to get GitHub Actions to run the updated workflows here. :confused:

2023-04-02 19:24 UTC, rasheedamir commented
Lets do it incrementally; we keep the current workflows as is and add new ones and when the new one has all features of the existing workflow then we can remove

We want to test and validate everything i.e. route; grafana dashboard; etc.

We use tilt to setup stuff on the SNO

2023-04-02 19:50 UTC, rasheedamir commented
also we have a plan that we should add real integration tests as well i.e. we deploy one sample application and then validate all of the resources are created and are valid with tests; so, we can guarantee 100% quality of this chart

2023-04-02 20:04 UTC, d3adb5 commented
> We want to test and validate everything i.e. route; grafana dashboard; etc.

I see! Does Tilt test those automatically when we run `tilt ci`? I'm pretty unfamiliar with Tilt, so it wasn't clear to me by looking at the current workflows.

2023-07-05 11:30 UTC, aslafy-z approved these changes, later dismissed

2023-07-11 12:42 UTC, mustafaStakater commented
how do we plan on making the missing crds available in kind?

2023-07-11 14:08 UTC, rasheedamir requested changes
Missing CRDs in kind how do we resolve it? Also the goal is that we are testing on real cluster so, can guarantee the quality of the chart

2023-07-26 08:20 UTC, karl-johan-grahn commented
Talked about it at Open Source pruning session today:
- Review the need for this change
- Feasibility of installing all CRDs on a temporary cluster

2025-08-19 10:04 UTC, aslafy-z commented
I would like to revive this PR.
The openshift builds often fails (the build workflow is not starting atm because of the selfhosted runner being somehow unavailable). 
It's a bit of a pain to ping the stakater team every now and then to fix these.

2026-05-09 14:15 UTC, closed without merging