Allow loadbalancer service external IP
stakater/application pull request #275
Opened 2023-09-26 11:23 UTC by YonatanRubin

2023-09-26 13:26 UTC, mustafaStakater commented
make a dummy commit so that latest pr pipeline is run `git commit -m "trigger pipeline" --allow-empty`

2023-09-26 19:28 UTC, rasheedamir commented
@aslafy-z can you plz review it?

2023-09-26 20:00 UTC, d3adb5 requested changes
I suggested a few minor changes, one of which looks like a necessary fix. Let me know if you need help implementing any of this, @YonatanRubin. Thank you for working on this!

2023-09-29 20:16 UTC, rasheedamir commented
@YonatanRubin can you plz take care of the comments?

2023-09-29 21:46 UTC, YonatanRubin commented
Hi, sorry I will not be able to handle this in the next couple of weeks, I will work on this then. If you prefer you can close the PR and I will open a new one when I can.

2023-10-11 20:02 UTC, rasheedamir commented
@YonatanRubin you can fix when you have time no problem

2024-01-07 16:33 UTC, rasheedamir commented
@d3adb5 @aslafy-z can anyone of you please finalize this PR and get it merged?

2024-01-07 22:22 UTC, d3adb5 commented on application/templates/service.yaml
> +  {{- end }}
Resolved in e90b5d3.

2024-01-07 22:23 UTC, d3adb5 commented on application/templates/service.yaml
> +  {{- end }}
Added as a feature in 5488bbc.

2024-01-07 22:30 UTC, d3adb5 commented on application/templates/service.yaml
>  {{- end }}
Done in 0bd9dab.

2024-01-07 22:31 UTC, d3adb5 commented
@rasheedamir @aslafy-z I pushed commits addressing the issues I raised in my last review. Since it would be presumptuous of me to give myself a green light, could either of you take a quick look and merge if possible?

2024-01-08 17:46 UTC, aslafy-z approved these changes
LGTM, thank you @d3adb5!

2024-01-08 17:48 UTC, merged