feat: allow usage of existing service account
stakater/application pull request #363
Opened 2024-11-15 11:25 UTC by aslafy-z

2025-01-07 02:05 UTC, d3adb5 requested changes
Left a few comments. I like the idea of adding a semantic value like this, but I feel the way it currently is introduces more confusion than clarity. I expanded upon this in one of the threads I opened below.

2025-01-07 02:05 UTC, d3adb5 commented on application/templates/_helpers.tpl
> +    {{- default "null" .Values.rbac.existingServiceAccountName }}
Edge case, may or may not be something to take into consideration: service accounts named `null`. Also, we're assuming the result of this partial template to be interpreted as YAML rather than a raw string, that may create confusion.

```suggestion
    {{- $saName := .Values.rbac.existingServiceAccountName }}
    {{- empty $saName | ternary (quote $saName) "null" }}
```

2025-01-07 02:05 UTC, d3adb5 commented on application/templates/_helpers.tpl
> +{{- define "application.service-account-name" }}
This partial template (or whatever replaces it) needs to be used in `application/templates/rolebinding.yaml` as well and anywhere else where `template "application.name" $` (+ other branches) was used to come up with a service account name.

Would be good to add test cases for the templates that use it, though that might lead to duplicated tests.

2025-01-22 19:28 UTC, aslafy-z commented on application/templates/_helpers.tpl
> +{{- define "application.service-account-name" }}
I simplified this template a lot and used it anywhere it a service account was needed.

2025-01-22 19:29 UTC, aslafy-z commented on application/templates/_helpers.tpl
> +    {{- default "null" .Values.rbac.existingServiceAccountName }}
the partial now only returns strings, do you think i should still quote the output?

2025-01-22 19:33 UTC, aslafy-z commented on application/templates/_helpers.tpl
> +    {{- fail "Conflict: 'rbac.existingServiceAccountName' is set, but a new service account is being created. Please disable 'rbac.serviceAccount.enabled' or unset 'rbac.existingServiceAccountName'."
I renamed `enabled` to `create` for it to be aligned with what is done in the community. I personally don't care about breaking changes if they are clearly indicated as such and major is bumped. I prefer to consistent and easily understandable APIs, over over-engineering for compatible solutions, even if it come with the cost of a breaking change. This is my personal take, I think it works for this chart. WDYT?

2025-02-07 05:31 UTC, d3adb5 requested changes
Final set of comments,  I promise. Reminder to add a unit test for it if you do take the suggestion. Otherwise, LGTM.

2025-02-07 05:31 UTC, d3adb5 commented on application/templates/cronjob.yaml
> +          serviceAccountName: {{ include "application.serviceAccountName" $ }}
This may be another feature, but personally, I think we should add this:

```suggestion
          automountServiceAccountToken: {{ $.Values.rbac.enabled }}
          serviceAccountName: {{ include "application.serviceAccountName" $ }}
```

If RBAC is disabled, we shouldn't even allow mounting tokens for the default service account, I'd say. What do you think?

2025-02-07 05:31 UTC, d3adb5 commented on application/templates/deployment.yaml
> +      serviceAccountName: {{ include "application.serviceAccountName" $ }}
Same comment as in the other thread.

```suggestion
      automountServiceAccount: {{ $.Values.rbac.enabled }}
      serviceAccountName: {{ include "application.serviceAccountName" $ }}
```

2025-02-07 05:31 UTC, d3adb5 commented on application/templates/job.yaml
> +      serviceAccountName: {{ include "application.serviceAccountName" $ }}
Same comment as in the other threads.

```suggestion
      automountServiceAccount: {{ $.Values.rbac.enabled }}
      serviceAccountName: {{ include "application.serviceAccountName" $ }}
```

2025-02-07 05:35 UTC, d3adb5 commented on application/templates/_helpers.tpl
> +    {{- default "null" .Values.rbac.existingServiceAccountName }}
I think it's a good idea, yes, since the output is supposed to be a string.

2025-02-21 18:05 UTC, rasheedamir commented
@aslafy-z lets finalize and get this merged

2025-04-18 13:27 UTC, aslafy-z commented on application/templates/cronjob.yaml
> +          serviceAccountName: {{ include "application.serviceAccountName" $ }}
Sounds good to me,  that seems like a reasonable assumption.

2025-07-09 18:11 UTC, karl-johan-grahn commented
@aslafy-z Can you please resolve the conflicts?

2025-07-09 20:12 UTC, rasheedamir commented
@d3adb5 can you plz review it again and approve it?

2025-08-11 01:37 UTC, d3adb5 approved these changes, later dismissed
LGTM! Sorry for the delay in coming back to this.

2025-08-11 01:38 UTC, d3adb5 commented
**Do make sure to do a major version bump afterwards!**

2025-08-19 09:09 UTC, aslafy-z commented
@rasheedamir @karl-johan-grahn Can you please also review? This PR needs a second approval.
@d3adb5 Thank you for taking some time to look at this PR!

2026-05-13 17:00 UTC, aslafy-z commented
@copilot resolve the merge conflicts in this pull request

2026-05-13 17:12 UTC, aslafy-z commented
@copilot resolve the merge conflicts in this pull request

2026-05-13 18:27 UTC, merged