feat: add dnsPolicy support to Deployment
stakater/application pull request #366
Opened 2024-11-24 22:02 UTC by tomjo

Fixes #365 

If wanted, I can also add it to job and cronjob but perhaps then support for dnsConfig should be added there as well?

2024-11-24 22:21 UTC, aslafy-z commented
I think adding `dnsConfig` too would be a nice addition. Also, I would prefer them to be added to deployments, jobs and cronjob at the same time. Can you do these changes?
Please use `make build-docs` to update the readme file.

2024-11-24 22:54 UTC, aslafy-z requested changes

2024-11-24 22:54 UTC, aslafy-z commented on application/values.yaml
> +  dnsPolicy: ClusterFirst
I would use the kubernetes default by default, by setting this value to an empty string (`""`).

2024-11-24 22:54 UTC, aslafy-z commented on application/values.yaml
>    # @default -- See below
Please add dnsPolicy and dnsConfig to jobs and cronjobs sections.

2024-11-25 01:26 UTC, aslafy-z approved these changes

2024-12-31 08:32 UTC, rasheedamir approved these changes

2024-12-31 08:32 UTC, rasheedamir commented
@aslafy-z you can merge it now

2024-12-31 09:13 UTC, aslafy-z approved these changes

2024-12-31 09:18 UTC, merged