made cert manager certificate's commonName optional
stakater/application pull request #369
Opened 2024-12-31 08:24 UTC by owais-rehman

2024-12-31 08:40 UTC, rasheedamir commented
also according to the documentation it seems one doesn't need to set the commonName for the leaf certificates which belong to the applications

2024-12-31 08:41 UTC, rasheedamir commented on README.md
> +| certificate.commonName | string | `nil` | Common name as specified on the DER encoded CSR. |
@owais-rehman maybe you can update the description and mention that it is not required/recommended for leaf certificates which this application CR presents

2024-12-31 14:27 UTC, aslafy-z requested changes

2024-12-31 14:27 UTC, aslafy-z commented on application/values.yaml
>    # -- (string) Common name as specified on the DER encoded CSR.
Please add the documentation in this value file, the readme is generated by make build-docs.

2025-01-01 09:52 UTC, owais-rehman commented on application/values.yaml
>    # -- (string) Common name as specified on the DER encoded CSR.
Done!

2025-01-01 16:10 UTC, rasheedamir approved these changes

2025-01-01 23:36 UTC, aslafy-z requested changes

2025-01-01 23:36 UTC, aslafy-z commented on application/values.yaml
> +  # -- (string) Private key algorithm of the corresponding private key for this certificate. This field is not recommended in cases when this certificate is an end-entity certificate. More informatio
This should be moved to the common name comment

2025-01-02 05:25 UTC, owais-rehman commented on application/values.yaml
> +  # -- (string) Private key algorithm of the corresponding private key for this certificate. This field is not recommended in cases when this certificate is an end-entity certificate. More informatio
Thanks for pointing out
Done!

2025-01-02 06:06 UTC, aslafy-z commented on application/values.yaml
> +  # admin-app
```suggestion
  # commonName: admin-app
```

2025-01-02 06:13 UTC, aslafy-z commented on README.md
> +| certificate.commonName | string | `nil` | Common name as specified on the DER encoded CSR. This field is not recommended in cases when this certificate is an end-entity certificate. More informatio
```suggestion
| certificate.commonName | string | `nil` | Common name as specified on the DER encoded CSR. This field is not recommended in cases when this certificate is an end-entity certificate. More information can be found in the [cert-manager documentation](https://cert-manager.io/docs/usage/certificate/#:~:text=%23%20Avoid%20using%20commonName,%3A%20example.com). |
```

2025-01-02 06:13 UTC, aslafy-z commented on application/values.yaml
> +  # -- (string) Common name as specified on the DER encoded CSR. This field is not recommended in cases when this certificate is an end-entity certificate. More information can be found [here](https:
```suggestion
  # -- (string) Common name as specified on the DER encoded CSR. This field is not recommended in cases when this certificate is an end-entity certificate. More information can be found in the [cert-manager documentation](https://cert-manager.io/docs/usage/certificate/#:~:text=%23%20Avoid%20using%20commonName,%3A%20example.com).
```

2025-01-02 06:15 UTC, aslafy-z approved these changes

2025-01-02 06:16 UTC, aslafy-z commented on application/values.yaml
> +  # -- (string) Common name as specified on the DER encoded CSR. This field is not recommended in cases when this certificate is an end-entity certificate. More information can be found in the [cert-
```suggestion
  # -- (tpl/string) Common name as specified on the DER encoded CSR. This field is not recommended in cases when this certificate is an end-entity certificate. More information can be found in the [cert-manager documentation](https://cert-manager.io/docs/usage/certificate/#:~:text=%23%20Avoid%20using%20commonName,%3A%20example.com).
```

2025-01-02 06:17 UTC, aslafy-z commented on README.md
> +| certificate.commonName | string | `nil` | Common name as specified on the DER encoded CSR. This field is not recommended in cases when this certificate is an end-entity certificate. More informatio
```suggestion
| certificate.commonName | tpl/string | `nil` | Common name as specified on the DER encoded CSR. This field is not recommended in cases when this certificate is an end-entity certificate. More information can be found in the [cert-manager documentation](https://cert-manager.io/docs/usage/certificate/#:~:text=%23%20Avoid%20using%20commonName,%3A%20example.com). |
```

2025-01-02 06:19 UTC, aslafy-z commented
I'm wondering if the field in the certificate value reacts correctly to a null value 
We might want to add a guard to prevent null values to enter the templating helperml.

2025-01-03 06:24 UTC, owais-rehman commented
Is there anything left to modify before you guys can approve this PR?

2025-01-03 14:02 UTC, aslafy-z commented
Can you please check my previous comment, have you done some tests ? Can you implement a unit test ?

2025-01-06 09:27 UTC, owais-rehman commented
> I'm wondering if the field in the certificate value reacts correctly to a null value

I have tried by setting `commonName` in certificate to `null` vs removing this field completely. In both case `tls.crt` gets populated with one of the `SAN` value. So I think we are good in that regard. 

> We might want to add a guard to prevent null values to enter the templating helperml.

I am not exactly sure what changes do I need to make for this. But should we keep this PR open till this change is made?
Suggestions?

2025-01-06 11:13 UTC, aslafy-z commented
I made the test here: https://github.com/stakater/application/pull/370. It looks like it's ok.

This PR introduces a breaking change, I will make it bump major version. Thank you for your contribution!

2025-01-06 11:14 UTC, aslafy-z approved these changes

2025-01-06 11:18 UTC, rasheedamir approved these changes

2025-01-06 11:19 UTC, merged